### ISSUE TITLE
ansi-term-color-vector

### ISSUE THREAD

**Issue by asok** [caisah/seti-theme#3]
Hi,
isn't this [issue](https://github.com/belak/base16-emacs/issues/4) relevant to your code?
Also [this](https://github.com/waymondo/apropospriate-theme/commit/0096f55043219246885307157af5ef8a89fa4130) is for the same thing.

I would make a PR but unfortunately I don't know enough about Emacs theming.

**Comment by caisah** [comment]
Thanks for the feedback. [This](https://github.com/caisah/seti-theme/commit/cbfef2fc15d19ce4c8326e65fafdd61737077132) should fix it.
