### ISSUE TITLE
Font-lock-comment-face and (bold) cause trouble

### ISSUE THREAD

**Issue by flyck** [caisah/seti-theme#4]
This theme seems to break the html-export on current org-mode versions (e.g. Org mode version 9.0.5)
When uncommenting the following two lines that is fixed:
font-lock-comment-delimiter-face
font-lock-comment-face

This has been fine for me, its a quick fix, but now another problem has appeared when exporting while using this theme: org-mode cant seem to find the face "bold" on export.
The seti-theme has a bunch of :inherit (bold) settings which probably cause this, but I'm not sure.
Does anybody have an idea?

**Comment by caisah** [comment]
I can't seem to reproduce your behavior. Could you please detail your steps to see if I find the problem? 

Although the `bold` face is not defined by this theme, using it should default to the built-in one.
